services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build:
      target: development
    volumes:
      - ./backend:/app
    command: celery -A config worker -l info

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
